// This file is auto-generated by FlutterFire CLI (manually updated here).
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: 'AIzaSyCORqiUgvZ1sd7NIQ_Oz0KOW6CKaaW2nKU',
    appId: '1:233979300222:android:d2b79e2d14f7a2a531cb2f',
    messagingSenderId: '233979300222',
    projectId: 'voca-twin-6fcdf',
    storageBucket: 'voca-twin-6fcdf.firebasestorage.app',
    authDomain: 'voca-twin-6fcdf.firebaseapp.com',
    measurementId: null,
  );
}
